### ISSUE TITLE
Possible empty dataframe for certain epochs

### ISSUE THREAD

**Issue by knorma01** [dmbrady01/Monkey_frog#13]
In the new version of analye_data.py and combine_data.py I've been getting a few errors. One error- PlotAverageSignal() got an unexpected keyword argument 'xmin' and also index 0 is out of bounds for axis 0 with size 0.

**Comment by dmbrady01** [comment]
Ok, so walk me through how this happens, what is the data set you are loading?

Then you run process_data.py, analyze_data.py, then combine_data.py?

**Comment by knorma01** [comment]
So I'm running the wk10 variable ITI data first with process_data and here
with analyze data

**Comment by dmbrady01** [comment]
Add the folder into the dropbox and tell me any variables you set in process_data and analyze_data

**Comment by knorma01** [comment]
I get the same error with wk9 variable iti data which is already in dropbox
so lets use that. Process data seems to work fine.
For analyze_data...
epoch name = correct
event = iti_start
prewindow 2
post window 5
window_type=event
xmin,xmax, ymin,ymax, and smoothing window are None

**Comment by dmbrady01** [comment]
Did you make sure to put all the files in a Blk folder? That was causing those errors yesterday. I’ll take a look

**Comment by knorma01** [comment]
The data is in the correct folder organization because yesterday when I
used the analyze_data it worked fine on the data, but today I started using
the new analyze_data that added the smoothing function and xmin/xmax

**Comment by knorma01** [comment]
and When I take an "all_traces" data set and enter it into the
combined_analyze I get that error that plotAverage Signal got an unexpected
keyword argument 'xmin'

**Comment by dmbrady01** [comment]
So I’m not sure why this is the case for reading data (it uses code that I did not write), but if I changed the folder name and structure it worked on my end. Do you see the actual data files in wk9 and wk10? They are actually named something like:

TDT-LockinRX8-22Oct2014_20-4-15_DT4_1024173_Blk-3.Tdx

So I renamed the wk9 folder to be:
TDT-LockinRX8-22Oct2014_20-4-15_DT4_1024173

And then added a folder in there called:
Blk-3

Then put all the data in Blk-3. Notice that this folder system matches what the data is actually called. then for dpath, I put:

‘/mypath/to/monkey_frog/data/TDT-LockinRX8-22Oct2014_20-4-15_DT4_1024173’

Referencing the outside folder. That all works. Otherwise it has a hard time finding the data. I have no idea why this is the case and why it worked yesterday, but this works for me. Try it out.

**Comment by dmbrady01** [comment]
what is in all traces? attach that file here.

**Comment by dmbrady01** [comment]
These data organization issues are a nightmare. We really need to work on a systematic framework for organizing data especially since the function in neo that reads data is very particular.

**Comment by dmbrady01** [comment]
If you are still getting issues with the plotting aspect, update matploblib. You probably have a super outdated version.

**Comment by knorma01** [comment]
What's strange is that is all worked fine this morning when I was using the
previous analyze_data program but since I pushed it to update I've been
getting the error and can't even re analyze the data I could analyze this
morning, thats what I trying to figure out what happened.

**Comment by dmbrady01** [comment]
Did you have merge conflicts when you fetched these changes? I'm wondering if it incorporated some of the code but not all of it

**Comment by dmbrady01** [comment]
Yeah, that might be the issue. Give it a try. Do it on one of the older folders (not the variable ITI), like the early datasets you gave me. So what you should do is the following:

`git status` (in the command line)

it will list a bunch of files that have been modified, you can do

`git checkout -- <file name>`

that should revert them to before. then do 

`git fetch`

`git merge origin/master`

if that gives you issues, then delete your monkey_frog and git clone from my repo. dont worry about forking, that is just too confusing at this point

**Comment by knorma01** [comment]
Your suggestions fixed a lot of the problems except I still can't analyze variable iti data when aligning to the start of iti , but I can't align to when stimulus appears. The following variables gives me - file quantity.py line 364 Ret=super(Quantity, self)._getitem_(key) 

Index error: index 0 is out of bounds for axis 0 with size 0

Epoch name omission
Event iti_start
Prewindow 2
Postwindow 5
Window type is event

**Comment by dmbrady01** [comment]
Great. Are there any omission trials? Is this for wk9 (which I have) or wk10? After you run process_data, you will have a data frame named trials in your workspace. after running process_data, type:

(trials.results == 'omission').sum()

if that is 0, then there were no omission trials in the dataset. 

I was able to do wk9 for aligned with iti_start:

epoch_name = ‘omission’
event = ‘iti_start’
prewindow = 2
postwindow = 5
window_type = ‘event’


and with stimulus appears:

epoch_name = ‘omission’
event = ’stimulus_appears’
prewindow = 2
postwindow = 5
window_type = ‘event’

**Comment by dmbrady01** [comment]
@knorma01 Is everything okay now? Was there no 'omission' trials? I can make an issue for having some sort of alert when certain trial results don't happen - although this needs careful consideration to build.

**Comment by knorma01** [comment]
Hi Daniel- sorry for not updating. I was doing a mad rush of data analysis on Saturday morning before jumping on a bus to Boston. I still could not get the variable iti analysis to work when aligning to the iti_start and continued to get the same error I had been getting. There were plenty of omission incorrect and correct trials - I don't think we need to do that alert because 99% of the time there are a mixture of correct, incorrect , and omitted trials in a given session. 

For fixed iti data I could correctly align to the iti_start.
