### ISSUE TITLE
Analog signal plot smoothing

### ISSUE THREAD

**Issue by knorma01** [dmbrady01/Monkey_frog#9]
Hello- Could you add a smoothing option for the combine analyze? just for the plotting.

**Comment by dmbrady01** [comment]
What type of smoothing @knorma01?

**Comment by knorma01** [comment]
I recall you showed Hiro and I some smoothing function. I don't remember if it was a sliding average or a downsampling

**Comment by dmbrady01** [comment]
That was a moving average. I'll add that functionality, you will be able to specify the bin size in ms and it will do a moving average with the nearest size that it can (since it might not exactly fit with the sampling frequency).

**Comment by knorma01** [comment]
Perfect

**Comment by dmbrady01** [comment]
@knorma01 Ok, there is a smoothing function for plotting in analyze_data and combine_analyzed_data. If you dont want to smooth, set 
`smoothing_window=None`

otherwise set it to the bin size in ms, like:
`smoothing_window=500`
